# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date updated'),
        ),
    ]
