# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0003_auto_20180406_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote',
            new_name='type',
        ),
    ]
