# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import todo_pb2 as todo__pb2


class TodosStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddTodo = channel.unary_unary(
        '/todo.Todos/AddTodo',
        request_serializer=todo__pb2.Todo.SerializeToString,
        response_deserializer=todo__pb2.OperationResponse.FromString,
        )
    self.ListTodos = channel.unary_unary(
        '/todo.Todos/ListTodos',
        request_serializer=todo__pb2.ListTodosRequest.SerializeToString,
        response_deserializer=todo__pb2.TodosList.FromString,
        )
    self.DeleteTodo = channel.unary_unary(
        '/todo.Todos/DeleteTodo',
        request_serializer=todo__pb2.Todo.SerializeToString,
        response_deserializer=todo__pb2.OperationResponse.FromString,
        )
    self.UpdateTodo = channel.unary_unary(
        '/todo.Todos/UpdateTodo',
        request_serializer=todo__pb2.Todo.SerializeToString,
        response_deserializer=todo__pb2.OperationResponse.FromString,
        )


class TodosServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListTodos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateTodo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TodosServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddTodo': grpc.unary_unary_rpc_method_handler(
          servicer.AddTodo,
          request_deserializer=todo__pb2.Todo.FromString,
          response_serializer=todo__pb2.OperationResponse.SerializeToString,
      ),
      'ListTodos': grpc.unary_unary_rpc_method_handler(
          servicer.ListTodos,
          request_deserializer=todo__pb2.ListTodosRequest.FromString,
          response_serializer=todo__pb2.TodosList.SerializeToString,
      ),
      'DeleteTodo': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteTodo,
          request_deserializer=todo__pb2.Todo.FromString,
          response_serializer=todo__pb2.OperationResponse.SerializeToString,
      ),
      'UpdateTodo': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateTodo,
          request_deserializer=todo__pb2.Todo.FromString,
          response_serializer=todo__pb2.OperationResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'todo.Todos', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
